services:
  quiz_postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - quiz_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  quiz_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: quiz-api-image
    depends_on:
      quiz_postgres:
        condition: service_healthy

    environment:
      - ConnectionStrings__DefaultConnection=Host=quiz_postgres;Port=5432;Database=${POSTGRES_DB};Username=${DB_USER};Password=${DB_PASSWORD}

      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - '5000:8080'
    restart: always

volumes:
  quiz_postgres_data:
